# For more information on this configuration file, reference
#   the following sources:

#   The project that makes this documentation possible,
#   and where you will find all of the config for this file:
#   https://squidfunk.github.io/mkdocs-material/

#   The plug-in to the documentation project used here for
#   generating documentation pages off of code:
#   https://github.com/JakubAndrysek/mkdoxy
#   
#   - Jacob S. <jsimeone0105@gmail.com>

site_name: Argos CTRE Summer Swerve Docs
edit_uri: edit/main/docs
site_url: https://jpiscitello7351.github.io/CTRE-SwerveGen/
repo_url: https://github.com/JPiscitello7351/CTRE-SwerveGen/
docs_dir: docs
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

  # Font Configuration
  font:
    text: Ubuntu
    code: Ubuntu Mono
  features:
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow
    - toc.integrate
    - content.action.edit

  favicon: assets/favicon.png
  logo: assets/favicon.png
  # icon: 
    # logo: material/code-braces

  # Colors
  palette:
    # Dark theme
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: yellow
      accent: orange

    # Light theme
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: yellow
      accent: orange

# Navigation
# ========= THIS IS WHERE YOU ADD YOUR PAGES =========
nav:
  # "Home" is a top-level "tab" which is a collection of 
  #   documentation pages. You probably want to add your 
  #   pages here.
  # Entries have the format:
  # - <Title that shows up on website>: <filename>
  # See the below pages for more details
  - Home:
    - CTRE Swerve Example Repo: index.md
  - Tutorials:
    - Arcade Drive (Intro Programming): tutorials/arcade-drive.md
    - Creating an XRP Project: tutorials/XRP_project/tutorial_XRP_Project.md
    - XRP Tank Drive: tutorials/XRP_Tank_Drive/tutorial_XRP_tank_drive.md
    - XRP Run Code: tutorials/XRP_Run_Code/tutorial_XRP_run_code.md
    - XRP WPILib Overview: tutorials/XRP_WPILib/tutorial_XRP_WPILib.md
  # "Robot API" is the tab that contains all of the pages
  #   generated by the mkdoxy plugin that we are using to generate
  #   docs. Note that the 'annotated.md', 'files.md', 'links.md'
  #   files are spat out by the generator and their path is just
  #   the project name, followed by that file. 
  # This shouldn't needed to be messed with too much unless you
  #   want to add your own documentation that isn't
  #   auto-generated to this section, for stuff like tutorials
  #   in that case, see the explanation above "Home"
  - Robot-API:
    - 'Structure List': 'summer-robot-2025/annotated.md'
    - 'File List Index': 'summer-robot-2025/files.md'
    - 'Links': 'summer-robot-2025/links.md'

# ========= =========


plugins:
  - search
  - offline
  # MkDoxy - The plug-in used for generating docs from code
  - mkdoxy:
      projects:
        summer-robot-2025:
          src-dirs: ./src/main # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "*.cpp *.h*" # specify file patterns to filter out
            RECURSIVE: True # recursive search in source directories


use_directory_urls: true # Include .html extension in links

# Extensions
markdown_extensions:
  - attr_list
  # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator:
        !!python/name:material.extensions.emoji.to_svg # Code block highlighting


  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  # Used for math stuff (Latex)
  - javascripts/mathjax.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Used for math stuff (Latex)
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
